name: WorkifyStyling

on:
  push:
    branches: [development]

jobs:
  lintTest:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Lint and Prettier
        # To run multiple commands we do the following
        # run: |
        #   npm run lint
        #   npm run style:lint
        #   npm run style:prettier
        run: npm run style:all
