# name: WorkifyStyling

# on:
#   push:
#     branches: [main]

# jobs:
#   lintTest:
#     name: Styling
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone Repository
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: npm install

#       - name: Run Lint
#         run: npm run style:all

#       - name: Prettify code
#         uses: creyD/prettier_action@v4.2

name: WorkifyImageCompression

on:
  pull_request:
    branches: [main]
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  imageOptimize:
    name: OpImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          # The `GITHUB_TOKEN` is automatically generated by GitHub and scoped only to the repository that is currently running the action. By default, the action can’t update Pull Requests initiated from forked repositories.
          # See https://docs.github.com/en/actions/reference/authentication-in-a-workflow and https://help.github.com/en/articles/virtual-environments-for-github-actions#token-permissions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
